#! /usr/bin/env bash

# Check if at least one argument is provided

if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

aws s3api create-bucket --bucket "$1" --region us-east-1