#! /usr/bin/env bash
echo "===delete bucket==="
# Check if at least one argument is provided

if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

aws s3api delete-bucket --bucket "$1" --output text